# Generated by Django 4.2.27 on 2026-05-09 19:45

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS exam;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=20)),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit_sec', models.PositiveIntegerField()),
                ('attempts_limit', models.PositiveIntegerField(default=1)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('show_answers_after', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_to', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'экзамен',
                'verbose_name_plural': 'экзамены',
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('q_type', models.CharField(choices=[('single_choice', 'Один вариант'), ('text', 'Текстовый ответ')], max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'банк вопросов',
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответа',
                'db_table': 'question_options',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.subject'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('exam_question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('question_order', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='core.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_questions', to='core.question')),
            ],
            options={
                'verbose_name': 'вопрос экзамена',
                'verbose_name_plural': 'вопросы экзамена',
                'db_table': 'exam_questions',
                'ordering': ['exam', 'question_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('attempt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('submitted', 'Завершена'), ('expired', 'Просрочена'), ('cancelled', 'Отменена')], default='in_progress', max_length=20)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_sec', models.PositiveIntegerField()),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('score_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'попытка экзамена',
                'verbose_name_plural': 'попытки экзаменов',
                'db_table': 'exam_attempts',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.subject'),
        ),
        migrations.CreateModel(
            name='CorrectTextKey',
            fields=[
                ('key_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accepted_answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_text_keys', to='core.question')),
            ],
            options={
                'verbose_name': 'ключ текстового ответа',
                'verbose_name_plural': 'ключи текстовых ответов',
                'db_table': 'correct_text_keys',
            },
        ),
        migrations.CreateModel(
            name='CorrectChoiceKey',
            fields=[
                ('correct_choice_key_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_choice_keys', to='core.questionoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_choice_keys', to='core.question')),
            ],
            options={
                'verbose_name': 'ключ тестового ответа',
                'verbose_name_plural': 'ключи тестовых ответов',
                'db_table': 'correct_choice_keys',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('attempt_answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='core.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='core.questionoption')),
            ],
            options={
                'verbose_name': 'ответ в попытке',
                'verbose_name_plural': 'ответы в попытках',
                'db_table': 'attempt_answers',
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('enrollment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.subject')),
            ],
            options={
                'verbose_name': 'запись на предмет',
                'verbose_name_plural': 'записи на предметы',
                'db_table': 'subject_enrollments',
                'indexes': [models.Index(fields=['student'], name='idx_enrollments_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectenrollment',
            constraint=models.UniqueConstraint(fields=('subject', 'student'), name='uq_subject_enrollments_subject_student'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['teacher'], name='idx_subjects_teacher'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='idx_options_question'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject'], name='idx_question_bank_subject'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'question_order'], name='idx_exam_questions_order'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='uq_exam_questions_exam_question'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', '-start_at'], name='idx_attempts_student'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'student'], name='idx_attempts_exam_student'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject'], name='idx_exams_subject'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published'], name='idx_exams_published'),
        ),
        migrations.AddConstraint(
            model_name='correctchoicekey',
            constraint=models.UniqueConstraint(fields=('question', 'option'), name='uq_correct_choice_keys_question_option'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question'], name='idx_attempt_answers_question'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uq_attempt_answers_attempt_question'),
        ),
    ]
